"""Bounded governance error vocabulary."""

from __future__ import annotations


class GovernanceError(RuntimeError):
    """A validation failure that is safe to expose to an operator."""

    def __init__(self, code: str, detail: str = "") -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code}: {detail}" if detail else code)


REASON_CODES = frozenset(
    {
        "REGISTRY_SCHEMA_INVALID", "DUPLICATE_REGISTRY_ID", "DUPLICATE_YAML_KEY",
        "UNKNOWN_SCHEMA_FIELD", "INVALID_LIFECYCLE_TRANSITION", "FROZEN_BASELINE_DRIFT",
        "SOURCE_OWNERSHIP_GAP", "SOURCE_OWNERSHIP_OVERLAP", "UNDECLARED_IMPORT_EDGE",
        "UNRESOLVED_INTERNAL_EDGE", "DYNAMIC_IMPORT_UNDECLARED", "UNREGISTERED_DIRECT_DEPENDENCY",
        "LOCKFILE_DRIFT", "ORPHANED_LOCK_ENTRY", "MUTABLE_PROVENANCE", "PROVENANCE_UNRESOLVED",
        "LICENSE_UNRESOLVED", "REJECTED_DEPENDENCY_ACTIVE", "REFERENCE_ONLY_DEPENDENCY_ACTIVE",
        "AUTHORITY_ESCALATION", "UNDECLARED_NETWORK_WRITE", "UNDECLARED_SECRET_ACCESS",
        "RETENTION_UNKNOWN", "RETENTION_UNBOUNDED", "TOOLCHAIN_HASH_MISMATCH",
        "TOOLCHAIN_VERSION_MISMATCH", "TOOLCHAIN_EPHEMERAL_PATH", "TOOLCHAIN_REPARSE_POINT",
        "TOOLCHAIN_PROCESS_LEAK", "TOOLCHAIN_PORT_LEAK", "EVIDENCE_HASH_MISMATCH",
        "NONDETERMINISTIC_OUTPUT", "TOOLCHAIN_ARCHIVE_INVALID", "EVIDENCE_ARCHIVE_INVALID",
        "SECRET_SCAN_FAILED", "TOOLCHAIN_NOT_FOUND",
    }
)
