import { useCallback, useEffect, useMemo, useState } from "react";
import { api, post } from "./api";

type Navigate = (page: string) => void;

const display = (value: unknown) => value === null || value === undefined || value === "" ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value);
const short = (value: unknown) => { const text = display(value); return text.length > 110 ? `${text.slice(0, 107)}…` : text; };

export function EcosystemPage({ navigate }: { navigate: Navigate }) {
  const [data, setData] = useState<any>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void api<any>("/api/science/ecosystem").then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "Unavailable")); }, []);
  const targets: Record<string, string> = { soil: "Data Soil", sensors: "Wallet Sensors", hypotheses: "Hypothesis Lab", indicators: "Indicator Forge", experiments: "Experiments", confidence: "Confidence Engine", risk: "Execution + Risk", watchers: "Watchers + Alerts", control: "Overview" };
  return <div className="science-layout">
    <section className="panel ecosystem span-8"><div className="panel-title"><div><span className="eyebrow">BEELZEBUB SCIENTIFIC LOOP</span><h2>Ecosystem map</h2><p>Wallets are sensors. Indicators are knowledge. Trades are experiments. Models are accumulated evidence.</p></div></div>
      {error ? <p className="empty-note">{error}</p> : <div className="ecosystem-map">{(data?.nodes || []).map((node: any) => <button key={node.id} className={`organism ${String(node.state || "").toLowerCase()}`} onClick={() => targets[node.id] && navigate(targets[node.id])}><span>{node.label}</span><small>{node.state || "Unavailable"}</small></button>)}</div>}
      <div className="science-cycle">{(data?.cycle || ["Unavailable"]).map((step: string, index: number) => <span key={step}>{step}{index < (data?.cycle || []).length - 1 && <b>↓</b>}</span>)}</div>
    </section>
    <ScienceRail health={data?.health} />
  </div>;
}

export function AutomatedSciencePage() {
  const [data, setData] = useState<any>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(() => { void api<any>("/api/science/automated").then((result) => { setData(result); setError(null); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unavailable")); }, []);
  useEffect(() => { load(); }, [load]);
  const control = async (path: string) => { setBusy(true); try { setData(await post<any>(path)); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Control unavailable"); } finally { setBusy(false); } };
  const queue = data?.queue?.states || {}; const counts = data?.counts || {}; const paused = Boolean(data?.worker_control?.paused);
  return <div className="science-layout"><section className="panel span-8"><div className="toolbar"><div><span className="eyebrow">D.6 AUTOMATED SCIENCE</span><h2>Continuous learning loop</h2><p className="muted">Durable research automation only. This control changes queue processing, never live or mainnet authority.</p></div><div><button className="button minor" onClick={load} disabled={busy}>Refresh</button>{paused ? <button className="button positive" onClick={() => void control("/api/science/resume")} disabled={busy}>Resume Research</button> : <button className="button warning" onClick={() => void control("/api/science/pause")} disabled={busy}>Pause Research</button>}</div></div>
    {error && <p className="empty-note science-message">Unavailable: {error}</p>}
    <div className="metric-grid"><Metric label="Worker" value={paused ? "PAUSED" : "READY"} /><Metric label="Queued" value={String((queue.PENDING || 0) + (queue.RETRYABLE || 0))} /><Metric label="Leased" value={String(queue.LEASED || 0)} /><Metric label="Observations" value={String(counts.observations || 0)} /><Metric label="Features" value={String(counts.feature_values || 0)} /><Metric label="Forward resolved" value={`${counts.resolved_forward_predictions || 0}/${counts.forward_predictions || 0}`} /><Metric label="Indicators" value={String(counts.indicators || 0)} /><Metric label="Models" value={String(counts.models || 0)} /></div>
    <section className="table-panel"><h3>Current loop</h3><div className="science-cycle">{["Observe", "Features", "Discover", "Historical", "Forward", "Promote", "Model", "Drift"].map((step, index, all) => <span key={step}>{step}{index < all.length - 1 && <b>↓</b>}</span>)}</div><p className="muted">{data?.scheduler || "Unavailable"}</p></section>
    <div className="table-scroll"><table><thead><tr><th>Stage</th><th>State</th><th>Updated</th><th>Detail</th></tr></thead><tbody>{(data?.stage_health || []).map((item: any) => <tr key={item.stage}><td>{item.stage}</td><td>{item.state}</td><td>{item.updated_at}</td><td title={display(item.detail)}>{short(item.detail)}</td></tr>)}{!(data?.stage_health || []).length && <tr><td colSpan={4} className="empty">No worker stage has run yet.</td></tr>}</tbody></table></div>
  </section><aside className="science-rail"><section className="panel"><span className="eyebrow">QUEUE TRUTH</span><h2>{paused ? "Paused" : "Durable"}</h2><dl className="metric-list">{Object.entries(queue).map(([state, count]) => <div key={state}><dt>{state}</dt><dd>{String(count)}</dd></div>)}</dl></section><section className="panel"><span className="eyebrow">RESOURCE STATE</span><dl className="metric-list"><div><dt>Hot free</dt><dd>{data?.resource_state?.hot_free_bytes ?? "—"} bytes</dd></div><div><dt>Cold archive</dt><dd>{data?.resource_state?.state || "Unavailable"}</dd></div><div><dt>Mode</dt><dd>{data?.execution_mode || "Unavailable"}</dd></div></dl></section></aside></div>;
}

export function DataIgnitionPage() {
  const [data, setData] = useState<any>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => { void api<any>("/api/science/data-ignition").then((value) => { setData(value); setError(null); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unavailable")); }, []);
  useEffect(() => { load(); }, [load]);
  const coverage = data?.coverage || {}; const manifest = data?.manifest || {}; const freshness = data?.freshness || {}; const counts = data?.counts || {}; const storage = data?.storage || {};
  return <div className="science-layout"><section className="panel span-8"><div className="toolbar"><div><span className="eyebrow">D.7 DATA IGNITION</span><h2>Historical commissioning</h2><p className="muted">Official source manifest, quality proof, D.6 evidence counts, and public-observer freshness. This view cannot acquire data or enable capital movement.</p></div><button className="button minor" onClick={load}>Refresh</button></div>
    {error && <p className="empty-note science-message">Unavailable: {error}</p>}
    <div className="metric-grid"><Metric label="Readiness" value={data?.readiness || "NO_DATA"} /><Metric label="Health" value={data?.health || "SOURCE_UNAVAILABLE"} /><Metric label="Coverage" value={`${(Number(coverage.coverage_fraction || 0) * 100).toFixed(1)}%`} /><Metric label="Coverage state" value={coverage.state || "UNPROVEN"} /><Metric label="Hours verified" value={`${manifest.verified || 0}/${coverage.expected_hours || 0}`} /><Metric label="Missing / failed" value={`${manifest.missing || 0} / ${manifest.failed || 0}`} /><Metric label="Observations" value={String(counts.observations || 0)} /><Metric label="Feature values" value={String(counts.feature_values || 0)} /></div>
    <section className="table-panel"><h3>Requested historical range</h3><dl className="metric-list"><div><dt>Start</dt><dd>{data?.requested_range?.start || "—"}</dd></div><div><dt>End</dt><dd>{data?.requested_range?.end || "—"}</dd></div><div><dt>Bytes downloaded</dt><dd>{manifest.bytes_downloaded ?? 0}</dd></div><div><dt>First / last event</dt><dd>{coverage.first_event_at || "—"} / {coverage.last_event_at || "—"}</dd></div><div><dt>Wallet / market observations</dt><dd>{counts.wallet_observations || 0} / {counts.market_observations || 0}</dd></div><div><dt>Outcome labels</dt><dd>{counts.outcome_labels || 0}</dd></div><div><dt>Forward predictions</dt><dd>{counts.forward_resolved || 0} / {counts.forward_predictions || 0} resolved</dd></div><div><dt>Science queue</dt><dd>{JSON.stringify(data?.queue?.states || {})}</dd></div></dl></section>
    <section className="table-panel"><h3>Freshness and storage</h3><dl className="metric-list"><div><dt>Last wallet observation</dt><dd>{freshness.last_wallet_observation || "—"}</dd></div><div><dt>Last market observation</dt><dd>{freshness.last_market_observation || "—"}</dd></div><div><dt>Last historical hour verified</dt><dd>{freshness.last_historical_hour_verified || "—"}</dd></div><div><dt>Coverage lag</dt><dd>{freshness.coverage_lag_seconds ?? "—"} seconds</dd></div><div><dt>Live receive lag</dt><dd>{freshness.live_receive_lag_seconds ?? "—"} seconds</dd></div><div><dt>E hot free</dt><dd>{storage.hot_free_bytes ?? "—"} bytes</dd></div><div><dt>D cold state</dt><dd>{storage.state || "Unavailable"}</dd></div></dl></section>
  </section><aside className="science-rail"><section className="panel"><span className="eyebrow">SOURCE CAPABILITY</span><h2>Evidence limits</h2><div className="table-scroll"><table><thead><tr><th>Evidence</th><th>Historical</th><th>Live</th></tr></thead><tbody>{(data?.source_capabilities || []).map((row: any) => <tr key={row.evidence}><td>{row.evidence}</td><td>{row.historical}</td><td>{row.live_current}</td></tr>)}</tbody></table></div></section><section className="panel"><span className="eyebrow">NON-NEGOTIABLE</span><p className="muted">Unavailable spread, depth, and liquidation evidence remains unavailable. It is never filled with zero or guessed.</p></section></aside></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="metric-card"><span>{label}</span><strong>{value}</strong></div>; }

export function ScienceResourcePage({ endpoint, title, subtitle, columns, search }: { endpoint: string; title: string; subtitle: string; columns: string[]; search?: boolean }) {
  const [data, setData] = useState<any>(null); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState("");
  const load = useCallback(() => { const suffix = search && query ? `?search=${encodeURIComponent(query)}` : ""; void api<any>(`${endpoint}${suffix}`).then((result) => { setData(result); setError(null); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unavailable")); }, [endpoint, query, search]);
  useEffect(() => { load(); }, [load]);
  const shownColumns = columns.length ? columns : ["state", "database", "execution_mode", "storage"];
  const items = Array.isArray(data?.items) ? data.items : data ? [data] : [];
  return <section className="panel table-panel science-table"><div className="toolbar"><div><div><span className="eyebrow">SCIENTIFIC READ MODEL</span><h2>{title}</h2><p className="muted">{subtitle}</p></div>{search && <input aria-label="Search graveyard" placeholder="Search rejected hypotheses" value={query} onChange={(event) => setQuery(event.target.value)} />}</div><button className="button minor" onClick={load}>Refresh</button></div>
    {error ? <p className="empty-note science-message">Unavailable: {error}</p> : <div className="table-scroll"><table><thead><tr>{shownColumns.map((column) => <th key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{items.map((item: any, index: number) => <tr key={item.id || item.wallet || item.hypothesis_id || item.experiment_id || item.indicator_id || item.model_id || item.decision_id || index}>{shownColumns.map((column) => <td key={column} title={display(item[column])}>{short(item[column])}</td>)}</tr>)}{!items.length && <tr><td colSpan={shownColumns.length} className="empty">{data?.empty_state || "No evidence"}</td></tr>}</tbody></table></div>}
  </section>;
}

export function ConfidencePage() {
  const [data, setData] = useState<any>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void api<any>("/api/confidence").then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "Unavailable")); }, []);
  const items = data?.items || [];
  const points = useMemo(() => items.slice().reverse().map((item: any) => Number(item.payload?.effective_confidence)).filter((item: number) => Number.isFinite(item)), [items]);
  const path = useMemo(() => points.length < 2 ? "" : points.map((point: number, index: number) => `${index ? "L" : "M"}${index / (points.length - 1) * 100} ${95 - point * 90}`).join(" "), [points]);
  return <div className="science-layout"><section className="panel span-8"><div className="panel-title"><div><span className="eyebrow">CALIBRATED NOWCAST</span><h2>Confidence Engine</h2><p>Model confidence is evidence quality; trade confidence is the current calibrated net-positive probability; effective confidence shrinks uncertainty toward 0.5.</p></div></div>{error ? <p className="empty-note">Unavailable: {error}</p> : <><div className="confidence-chart">{path ? <svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d={path} fill="none" stroke="var(--gold-bright)" strokeWidth="1.5" vectorEffect="non-scaling-stroke" /></svg> : <p className="empty-note">{data?.empty_state || "No evidence"}</p>}</div><div className="table-scroll"><table><thead><tr><th>Symbol</th><th>Model confidence</th><th>Trade confidence</th><th>Effective confidence</th><th>Expected net edge</th><th>Alpha survival</th><th>Decision</th></tr></thead><tbody>{items.map((item: any) => <tr key={item.decision_id}><td>{item.symbol}</td><td>{display(item.payload?.model_confidence)}</td><td>{display(item.payload?.trade_confidence)}</td><td>{display(item.payload?.effective_confidence)}</td><td>{display(item.payload?.expected_net_edge)}</td><td>{display(item.payload?.alpha_survival)}</td><td>{item.decision}</td></tr>)}{!items.length && <tr><td colSpan={7} className="empty">{data?.empty_state || "No evidence"}</td></tr>}</tbody></table></div></>}</section><ScienceRail /></div>;
}

export function ScienceRail({ health }: { health?: any }) {
  const [data, setData] = useState<any>(health || null);
  useEffect(() => { if (!health) void api<any>("/api/science/health").then(setData).catch(() => setData(null)); }, [health]);
  const storage = data?.storage || {};
  return <aside className="science-rail"><section className="panel"><span className="eyebrow">ECOSYSTEM HEALTH</span><h2>{data?.state || "Unavailable"}</h2><dl className="metric-list"><div><dt>Mode</dt><dd>{data?.execution_mode || "Unavailable"}</dd></div><div><dt>Cold archive</dt><dd>{storage.state || "Unavailable"}</dd></div><div><dt>Hot spool</dt><dd>{storage.spool ? `${storage.spool.files} files` : "—"}</dd></div><div><dt>Forward predictions</dt><dd>{data?.counts?.science_forward_predictions ?? "—"}</dd></div><div><dt>Risk state</dt><dd>Simulation only</dd></div></dl></section><section className="panel"><span className="eyebrow">NON-NEGOTIABLE</span><p className="muted">No UI action can arm live capital movement. Raw wallet observations require the validated indicator → model → edge → risk path.</p></section></aside>;
}
