"""Phase E scientific-experiment foundation.

The package reads immutable Phase D corpus provenance and persists its own
append-only scientific ledger.  It intentionally exposes no prediction,
signal, execution, or capital-allocation capability.
"""

from .ledger import CorpusProvenanceError, ExperimentConflictError, LedgerIntegrityError, PhaseELedger
from .generation import (
    E3_GENERATOR_ALGORITHM,
    E3_GENERATOR_CODE_VERSION,
    PREDICATE_COMPLEMENT_WITHIN_PARTITION_V1,
    GenerationConflictError,
    GenerationError,
    GenerationIntegrityError,
    GenerationRunSpec,
    GenerationStatus,
    HypothesisFamilySpec,
    HypothesisProposal,
    OutcomeAccessError as GenerationOutcomeAccessError,
    PhaseEHypothesisGenerator,
    Predicate,
    PredicateOperator,
    StatisticalTestPlan,
    ThresholdPolicy,
    wallet_action_sign_family,
)
from .materialization import (
    ALL_ELIGIBLE_V1,
    DETERMINISTIC_HASH_V1,
    TIME_STRATIFIED_HASH_V1,
    TIME_STRATIFIED_HASH_V2,
    EligibilitySpec,
    MaterializationConflictError,
    MaterializationIntegrityError,
    MaterializationSpec,
    MaterializationStatus,
    OutcomeAccessError,
    OutcomeResolutionSpec,
    PhaseEMaterializer,
    SourceUniverseProvenance,
    StratificationSpec,
)
from .runner import NullExperimentRunner
from .types import (
    ExperimentConclusion,
    ExperimentResult,
    ExperimentStatus,
    FeatureReference,
    HypothesisDefinition,
    OutcomeHorizon,
    PartitionIdentity,
    PromotionState,
    RejectionReason,
    StatisticSpec,
)

__all__ = [
    "CorpusProvenanceError",
    "E3_GENERATOR_ALGORITHM",
    "E3_GENERATOR_CODE_VERSION",
    "ALL_ELIGIBLE_V1",
    "DETERMINISTIC_HASH_V1",
    "ExperimentConflictError",
    "ExperimentConclusion",
    "ExperimentResult",
    "ExperimentStatus",
    "GenerationConflictError",
    "GenerationError",
    "GenerationIntegrityError",
    "GenerationOutcomeAccessError",
    "GenerationRunSpec",
    "GenerationStatus",
    "EligibilitySpec",
    "FeatureReference",
    "HypothesisDefinition",
    "HypothesisFamilySpec",
    "HypothesisProposal",
    "LedgerIntegrityError",
    "MaterializationConflictError",
    "MaterializationIntegrityError",
    "MaterializationSpec",
    "MaterializationStatus",
    "NullExperimentRunner",
    "OutcomeAccessError",
    "OutcomeResolutionSpec",
    "OutcomeHorizon",
    "PartitionIdentity",
    "PhaseELedger",
    "PhaseEHypothesisGenerator",
    "PhaseEMaterializer",
    "PromotionState",
    "PREDICATE_COMPLEMENT_WITHIN_PARTITION_V1",
    "Predicate",
    "PredicateOperator",
    "RejectionReason",
    "StatisticSpec",
    "StatisticalTestPlan",
    "SourceUniverseProvenance",
    "StratificationSpec",
    "TIME_STRATIFIED_HASH_V1",
    "TIME_STRATIFIED_HASH_V2",
    "ThresholdPolicy",
    "wallet_action_sign_family",
]
